# Etapa 1: Construir a aplicação Angular
FROM node:20 AS build

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY frontend/package*.json ./

# Instalar o Angular CLI globalmente
RUN npm install -g @angular/cli

# Instalar as dependências do projeto (inclui o Angular CLI se necessário)
RUN npm install

# Copiar o restante do código da aplicação
COPY frontend/ ./

# Criar o build da aplicação Angular
RUN ng build

# Etapa 2: Servir a aplicação com um servidor NGINX
FROM nginx:alpine

# Copiar os arquivos de build para o NGINX
COPY --from=build /app/dist/balcaouff /usr/share/nginx/html

# Copiar o arquivo de configuração do NGINX com proxy reverso
COPY frontend/nginx.conf /etc/nginx/nginx.conf

# Expor a porta 80 (NGINX)
EXPOSE 3070

# Comando para rodar o NGINX
CMD ["nginx", "-g", "daemon off;"]